import React from 'react'

type Props = {}

const page = (props: Props) => {
  return (
    <div>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/lXBqid2LeKM?si=J_TVkZCnlRExlE7F" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/pEb65ePI0Lo?si=AxwaYyan00Jajh3q" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/d3FmsvxttNI?si=d5oXmdc9mPWucst8" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/EJ8eRwq7-IA?si=WnIG5VnTHlaYXzvv" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/eQqJkm_q93k?si=Tc5Qld62U13l5k6k" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/wgD8h0ueJFQ?si=OoQ6be1ZM_HC5Bv8" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/yyaxduBu_2k?si=VWhvc0PAultD3yQT" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/ZkTzLruFDnM?si=y4RPdQWWwXUmr-zn" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/QzAub_EjkZU?si=OACoUISeTnOi68aK" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/VX8EOlOO7Ek?si=0ybW-voQo5wgOMAs" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/KXWot5eeqoM?si=Z0ovSldBF4gb1-MA" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/PDQZ9C7yuDg?si=hJ7_QyyYbvyOhsuT" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/X7Z3uj_NWDA?si=bEWejhdNkKPg59gs" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/S1-17TeZvV0?si=6R8emTAeHYE0yZeQ" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/YB9c34jAJKo?si=_gqumFXWj_CwLitq" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/s723-3hkUjA?si=2FqhwNfL65P-P3Nk" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/9I2hBer91Gw?si=vFyjdXdB6l4AppVL" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/jgjcy04PDRM?si=FOfJexYpKp7Q4K_I" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/V7N2CXdSqks?si=1fMK1tLDpXGOdho5" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/_8zGxvOT6oQ?si=-V54vBF1gFNuFV6-" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/Bc5UHKO3wWc?si=YopP2UD-R51KpElD" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/qxVu1CfGNEo?si=iTOx67LTs3XnHJfH" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/VaTLi4ug5xI?si=RXA2S3qOzOYEWMqX" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/goMuN6CbZpU?si=EwKCqChFqGoayueF" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/i1g3gKtyztY?si=bjq0kZESvTv9hOfN" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/hbEA5sQbOUM?si=vqhjjQTjQXU1bZD2" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/qpeP4Er5PYE?si=D5Un9AMxkRa5lKwZ" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/4j5502DTo8s?si=3BUxfNOFA_HoiKwD" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/bB015XSTh6w?si=rEMdizzNz8qfvcXD" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/iVAOGx8NgJ0?si=QRoMaCTBeRWersy5" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/gyLCZECB8nI?si=_VIvcrSCV9a8jZF2" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/jsQrK46NSm8?si=3XhOhi6rWqvRovE2" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/AflNDhBUfBg?si=nQqeAqTL0-ybuYCI" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/nWCmqsr47t0?si=rH2P2mk2qO7a2thb" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/WZekox8qJI0?si=X6E28IjhkIfbipxC" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/nLi2INEBkCE?si=qTSCZxg1HFyZ95fB" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/pYiRq0rHvKE?si=1jgUfkD--2QO6VUg" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/UfI_iS6nniU?si=AEPmyUkneAaXPC28" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/PGPFPC5IZuw?si=nF7SqKr_MRuxGtie" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/zLVx7THQEpg?si=ya4m4XBTgasSRxCg" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/kSTL_OexiRY?si=e7YBQo8VwcmQteqC" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/_1qAmGdNaFA?si=9orTp1xHYFRsA9mY" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/2_ZZMHB3Vvc?si=Vk_wznlWPMdOW7ik" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/UY4c1Afh07Q?si=rdVIFsylZUGBru-X" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/cQDE9hJbd2w?si=LpXk-85bWPR61UCy" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/UyKUnK2xTGc?si=FeB0HtuiMILi2UxH" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/plawLVzCmFo?si=zbj906S0iSiQf_Xi" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/EKkbYEZcE7o?si=I5O1Shb8ewYG5Jil" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/XSjdMyy9IDc?si=ydxkrfyRBFpOnxdA" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/pREAeOHZQMU?si=OYkZWvZQkrT22j7n" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/6ByNA8X3roo?si=tVan5na0tSD0iFN6" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/2MmhjiPFuH4?si=MY6i702ApFwiBLvA" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/1Q1KbaQHHVw?si=eMexWEkKx0dZQMZ1" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/S4bZFcp59ao?si=4WCl-mJZU-Gkqpbq" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/5CHmS9zYovg?si=7NZg7jUTJn_vsNDi" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/8C3YJGHjU-I?si=ArDKkIOjJd5TgNkw" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/FDo8t4-KQaI?si=T5zp-LN0PtixdiJ8" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/RMvZyeC8DN4?si=o3v1qFmDNepDMHCX" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/tlHuhrXhCAc?si=9YxYSEuGecBAvMgt" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/NNi2OuO0oeE?si=_zWEsuvK-mqJEITJ" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/SHRp7cyc7iw?si=cFy21OmrVNZ13LBl" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/RECtnMQT3EI?si=hsb5tcQt6soIiNC8" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/BiPo7uwAGQg?si=Legy3Op-Xv1RL3gy" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/EsmxYjXJoj4?si=LSeOIznEHoGYz-ow" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/eWsNnfg1PJw?si=kxK78KPiaZ2qK7sQ" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/502rcWj7V7w?si=Y75Bfh64c_dXGvqc" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/6usdwGgJ458?si=57ri5LnzXFfQjBm0" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/kGvG5JgvGDk?si=B448vk6cEyM7GCoS" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/BxYYR3_0X_s?si=bbz7hbsrm7Lnf14Z" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/ylMjKAV3L_Q?si=kbH5oOPkNputAPAo" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/YuGJKo55ixQ?si=Z8ceb3dHCkLl5AIO" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/1QbADQKnJag?si=QWuJXHGKmx1mmNry" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/36LlJm3pEbc?si=hbW7CB6SjXKcXsPV" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/n2E7i881j9I?si=UiTg_a-PjbpLT_WB" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/WmPMf5hQwa8?si=9W68iGzc63rt9r5Y" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/gd_XQFNQUB4?si=p5_ks9v0tTBXnfXV" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/eM1ZVsZTMyU?si=xQwMOqXUSyN06z1b" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/IF2SUVtsc3E?si=SoBnwbM9stvXwpAM" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/f2V3TixP1I4?si=uToNgeV94UewfeCR" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/W6t4tjVrh3M?si=_nTPNNIWY7XsUD7F" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/RLwJTwptfTQ?si=vDGtVMvVFb-l_a3X" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/F6Ksr7LQoSA?si=inov1IDGR2UUo6aR" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/XUEYjOi01Hs?si=CGFgJYmwvKLeee5Q" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/DIRVtdnMc8c?si=xSHqYzTZQtSLE4Oo" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/UoNJf2KPQis?si=QtA22j2Wg_eiKsyT" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/7zQDmWOY6RY?si=_FWEkXD9_b2Tz28V" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/Usr6w0SakpI?si=RWPVwEFaBrLaFfEY" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/zUYz-lbuBNg?si=g8SKbuDFEFQdYz0l" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/LRluR7xj-mw?si=kBIYpxRidepFhHTH" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/uQcaNd07JtA?si=Ph5CYwhyGT44_Ap4" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/g6Qr4O5qFl8?si=w9KLmwmeOd1nowF6" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/NJvTPrmxkGQ?si=H3z_ayxzYK1ggtY2" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/5EnF50AloDE?si=2pIbisMnsLqbsZvL" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/DqzzmHPucDk?si=1eo_bOIIfNfs4S9l" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/0Muw_xkeyk0?si=SCwmml9a-hydnziN" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/Z6EflH-N64k?si=5iBiJUI3IFDoTmzr" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/JraY6WOK3Nc?si=pe0Nc5AKYzH-iu3R" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/A7gqGBqT3ek?si=-y4tqmPeq-5EhWlW" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/YnQTfZICAxQ?si=ui2QfYwIwL2FNqCF" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>  
          <iframe width="560" height="315" src="https://www.youtube.com/embed/M01SMUoHAd4?si=RXRtVRWtQB77syi0" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/3Pxonz9OAJw?si=tQc3-YhNBJeBfyZF" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/cQSbPjNj8Sk?si=EdFfN8ms9Z8osmSq" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/GbUZBwWXxXQ?si=2o-j3FT9yngt7PxY" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/nE0PCcmhtF8?si=rKzF-e9CQE1oFRYa" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/ofaZ56bL1j0?si=qCtV8TDnU5aDfO2c" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/-GO76eRhFQ8?si=ZPVwE6CwCU69VuIY" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/40_M0m4SFIk?si=WY8nKvbCpZY-Roip" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/M9_FqcTWSQY?si=qV4FcrHeCW_rPoZN" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/YMcYOEx78hk?si=s5inhyi3jHrI5SzL" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/IVpFjNbn56Y?si=LYYheFma2OVIUUjq" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/7oAX8eIwwN4?si=CpZCJUa6sPE0E6e6" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/NDYY9DJUESg?si=U8863Zbh3u0g2Pq-" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/IUv7abYrio0?si=KlaMKnJy_NmP9G8h" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/5M3OvbdoqMQ?si=nXmz7W3JqzR-RDD3" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/fd6C1cntyyo?si=EPE9zhlC09tjXtiJ" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/TA11riXVSe4?si=S3YZxEJdvUuNkkxb" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/lmGQTy-UcaM?si=MfVmrjrA39FXV4Ty" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/Fv3yYjq_9rk?si=u1mnZ2rdM2bAW4Wg" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>


          <iframe width="560" height="315" src="https://www.youtube.com/embed/JLaEGGVP08E?si=pXf8qP6LDjdrOc6_" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" ></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/6_HcshBWY88?si=00ATIMWYA5-23doe" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/pMnLYuogC3k?si=7JTJOmaNH_jLj2Ja" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/bon9uEdqOWU?si=HfYGjdRotbW6819e" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/SBsJdJDCvMk?si=kr1kIPpGLExCe1F6" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/iD_FBNIVDcs?si=8luTvneqeCuQDd8_" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/_1mp9m3UkQQ?si=_hSnD-K3u7LO0Ldj" title="YouTube video player"   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"      allowFullScreen></iframe>
    </div>
  )
}

export default page